name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "develop" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        python: ["3.10", "3.9", "3.8"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: python -m pip install uproot awkward matplotlib
      - name: Install pytest
        run: python -m pip install pytest
      - name: Run pytest
        run: pytest
